export const _BJLIST = [
    {
        "preferenceName": "卷板",
        "isExistChild": 0,
        "isHave": 1,
        "settingTypeId": 4,
        "isDefault": 1,
        "preferenceImgUrl": "",
        "preferenceId": 32,
        "tagTypeId": 6,
        "isFixed": 0,
        "preferenceSort": 1,
        "tagName": "今日报价",
        "childList": null,
        "isDefaultTag": 1,
        "itemId": 0
    },
    {
        "preferenceName": "中板",
        "isExistChild": 0,
        "isHave": 1,
        "settingTypeId": 4,
        "isDefault": 1,
        "preferenceImgUrl": "",
        "preferenceId": 33,
        "tagTypeId": 6,
        "isFixed": 0,
        "preferenceSort": 2,
        "tagName": "今日报价",
        "childList": null,
        "isDefaultTag": 0,
        "itemId": 0
    },
    {
        "preferenceName": "大中型材",
        "isExistChild": 0,
        "isHave": 1,
        "settingTypeId": 4,
        "isDefault": 1,
        "preferenceImgUrl": "",
        "preferenceId": 35,
        "tagTypeId": 6,
        "isFixed": 0,
        "preferenceSort": 3,
        "tagName": "今日报价",
        "childList": null,
        "isDefaultTag": 0,
        "itemId": 0
    },
    {
        "preferenceName": "H型钢",
        "isExistChild": 0,
        "isHave": 1,
        "settingTypeId": 4,
        "isDefault": 1,
        "preferenceImgUrl": "",
        "preferenceId": 36,
        "tagTypeId": 6,
        "isFixed": 0,
        "preferenceSort": 4,
        "tagName": "今日报价",
        "childList": null,
        "isDefaultTag": 0,
        "itemId": 0
    },
    {
        "preferenceName": "无缝管",
        "isExistChild": 0,
        "isHave": 1,
        "settingTypeId": 4,
        "isDefault": 1,
        "preferenceImgUrl": "",
        "preferenceId": 37,
        "tagTypeId": 6,
        "isFixed": 0,
        "preferenceSort": 5,
        "tagName": "今日报价",
        "childList": null,
        "isDefaultTag": 0,
        "itemId": 0
    },
    {
        "preferenceName": "建材",
        "isExistChild": 0,
        "isHave": 1,
        "settingTypeId": 4,
        "isDefault": 1,
        "preferenceImgUrl": "",
        "preferenceId": 34,
        "tagTypeId": 6,
        "isFixed": 0,
        "preferenceSort": 6,
        "tagName": "今日报价",
        "childList": null,
        "isDefaultTag": 0,
        "itemId": 0
    },
    {
        "preferenceName": "结构钢",
        "isExistChild": 0,
        "isHave": 1,
        "settingTypeId": 4,
        "isDefault": 1,
        "preferenceImgUrl": "",
        "preferenceId": 39,
        "tagTypeId": 6,
        "isFixed": 0,
        "preferenceSort": 7,
        "tagName": "今日报价",
        "childList": null,
        "isDefaultTag": 0,
        "itemId": 0
    },
    {
        "preferenceName": "直缝焊管",
        "isExistChild": 0,
        "isHave": 1,
        "settingTypeId": 4,
        "isDefault": 1,
        "preferenceImgUrl": "",
        "preferenceId": 38,
        "tagTypeId": 6,
        "isFixed": 0,
        "preferenceSort": 8,
        "tagName": "今日报价",
        "childList": null,
        "isDefaultTag": 0,
        "itemId": 0
    }
]